<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	
	<ItemGroup>
		<Content Include="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="AllOverIt.EntityFrameworkCore.Diagrams" Version="9.0.0-rc.8" />
		<PackageReference Include="AllOverIt.Logging" Version="9.0.0-rc.8" />
		<PackageReference Include="AllOverIt.EntityFrameworkCore" Version="9.0.0-rc.8" />
		<PackageReference Include="AllOverIt.GenericHost" Version="9.0.0-rc.8" />
		<PackageReference Include="Polly" Version="8.6.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Pot.Data\Pot.Data.csproj" />
	</ItemGroup>

</Project>
