<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AllOverIt.Logging" Version="9.0.0-rc.1" />
		<PackageReference Include="AllOverIt.EntityFrameworkCore" Version="9.0.0-rc.1" />
		<PackageReference Include="AllOverIt.GenericHost" Version="9.0.0-rc.1" />
		<PackageReference Include="Polly" Version="8.5.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Pot.Data\Pot.Data.csproj" />
	</ItemGroup>

</Project>
