<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AllOverIt.DependencyInjection" Version="9.2.0" />
		<PackageReference Include="AllOverIt.Logging" Version="9.2.0" />
		<PackageReference Include="MailKit" Version="4.16.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Pot.RazorComponents\Pot.RazorComponents.csproj" />
		<ProjectReference Include="..\Pot.Shared\Pot.Shared.csproj" />
	</ItemGroup>

</Project>
