<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AllOverIt.Csv" Version="9.0.0-rc.3" />
		<PackageReference Include="AllOverIt.Logging" Version="9.0.0-rc.3" />
		<PackageReference Include="AllOverIt.Validation" Version="9.0.0-rc.3" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\Pot.Data\Pot.Data.csproj" />
  </ItemGroup>

</Project>
