<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AllOverIt.Cryptography" Version="9.2.0" />
		<PackageReference Include="AllOverIt.Csv" Version="9.2.0" />
		<PackageReference Include="AllOverIt.Logging" Version="9.2.0" />
		<PackageReference Include="AllOverIt.Serialization.Binary" Version="9.2.0" />
		<PackageReference Include="AllOverIt.Validation" Version="9.2.0" />
		<PackageReference Include="TimeZoneConverter" Version="7.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Pot.Data\Pot.Data.csproj" />
		<ProjectReference Include="..\Pot.EmailSender\Pot.EmailSender.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Pot.App.Tests" />

		<!--Required for mocking ILogger<T> where T is internal-->
		<InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
	</ItemGroup>

</Project>
