<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AllOverIt.Cryptography" Version="9.0.0-rc.4.1" />
		<PackageReference Include="AllOverIt.Csv" Version="9.0.0-rc.4.1" />
		<PackageReference Include="AllOverIt.Logging" Version="9.0.0-rc.4.1" />
		<PackageReference Include="AllOverIt.Serialization.Binary" Version="9.0.0-rc.4.1" />
		<PackageReference Include="AllOverIt.Validation" Version="9.0.0-rc.4.1" />
		<PackageReference Include="TimeZoneConverter" Version="7.0.0" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\Pot.Data\Pot.Data.csproj" />
  </ItemGroup>

</Project>
