<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<PackageReference Include="AllOverIt.Serialization.Json.SystemText" Version="9.0.0-rc.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
		<PackageReference Include="Microsoft.Extensions.Telemetry" Version="9.5.0" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.4.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Pot.App\Pot.App.csproj" />
	  <ProjectReference Include="..\Pot.Data\Pot.Data.csproj" />
	</ItemGroup>
</Project>
