# version: "3.8"
services:
  postgres:
    container_name: pot-postgres
    build:
      context: Postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5444:5432"
    # Persist the database data on the host machine. The folder must exist.
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pot-network

  server:
    container_name: pot-aspnet
    build:
      # The context needs to be up one level so the server source code can be found
      context: ..
      dockerfile: Docker/Server/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DATABASE__HOST=pot-postgres
      - DATABASE__USERNAME=${POSTGRES_USER}
      - DATABASE__PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE__NAME=${POSTGRES_DB}
      - DATABASE__BACKUPPATH=${POSTGRES_BACKUP_PATH}
      - RSA__PRIVATEKEY=${RSA_PRIVATE_KEY}
      - ASPNETCORE_URLS=http://+:5241
      - JWT__ISSUER=${JWT_ISSUER}
      - JWT__AUDIENCE=${JWT_AUDIENCE}
      - JWT__SECRETKEY=${JWT_SECRET_KEY}
    ports:
      - "5241:5241"
    # Map the backups directory inside the container to a local directory
    # The folder must exist on the host machine
    volumes:
      - ./postgres-backups:/backups
    healthcheck:
      test: "wget -q --spider http://localhost:5241/_health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - pot-network

networks:
  pot-network:
    driver: bridge
