<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AllOverIt.DependencyInjection" Version="9.0.0" />
		<PackageReference Include="AllOverIt.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="AllOverIt.EntityFrameworkCore.Pagination" Version="9.0.0" />
		<PackageReference Include="EntityFrameworkCore.Exceptions.PostgreSQL" Version="8.1.3" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Pot.Shared\Pot.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Pot.App.Tests" />
	</ItemGroup>
</Project>
