<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AllOverIt" Version="9.0.0-rc.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.9" />
  </ItemGroup>
</Project>
