<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Emails\ApprovalRejected\ApprovalRejectedEmail.text" />
    <EmbeddedResource Include="Emails\ApprovalAccepted\ApprovalAcceptedEmail.text" />
    <EmbeddedResource Include="Emails\BudgetReminder\BudgetReminderEmail.text" />
    <EmbeddedResource Include="Emails\PendingApproval\PendingApprovalEmail.text" />
    <EmbeddedResource Include="Emails\ChangePassword\ChangePasswordEmail.text" />
    <EmbeddedResource Include="Emails\Invitation\InvitationEmail.text" />
    <EmbeddedResource Include="Emails\Signup\SignupEmail.text" />
  </ItemGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="AllOverIt" Version="9.2.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
