<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup>
		<!--IDE0063 - 'using' statement can be simplified-->
		<!--IDE0079 - remove unnecessary suppression-->
		<!--IDE0290 - use primary constructor-->
		<!--CS0618 - 'member' is obsolete-->
		<!--CA1873 - Evaluation of this argument may be expensive and unnecessary if logging is disabled-->
		<!--<NoWarn>$(NoWarn);IDE0063;IDE0079;IDE0290;CS0618</NoWarn>-->
		<NoWarn>$(NoWarn);IDE0290;CA1873</NoWarn>
	</PropertyGroup>

	<!-- Coverlet Code Coverage Exclusions -->
	<ItemGroup Condition="$(MSBuildProjectName.EndsWith('.Tests')) or $(MSBuildProjectName.EndsWith('.TestUtils'))">
		<AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
	</ItemGroup>
</Project>
